### ISSUE TITLE
Attempt to invoke virtual method on a null object reference

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/android-inventory-agent#101]
**Crash report for Inventory** 
(org.flyve.inventory.agent) v0.1.0 (39160)
Device LENOVO Lenovo TB2-X30F OS 6.0.1

```JSON
{
  "apiKey": "b6bc7ce0da33f92fe6c49c568af43963",
  "notifier": {
    "name": "Android Bugsnag Notifier",
    "version": "3.4.0",
    "url": "https://bugsnag.com"
  },
  "events": [
    {
      "payloadVersion": "2",
      "severity": "error",
      "metaData": {
        
      },
      "projectPackages": [
        "org.flyve.inventory.agent"
      ],
      "exceptions": [
        {
          "errorClass": "java.lang.NullPointerException",
          "message": "Attempt to invoke virtual method 'java.lang.String java.net.URL.toExternalForm()' on a null object reference",
          "stacktrace": [
            {
              "method": "org.flyve.inventory.agent.utils.HttpInventory$1.run",
              "file": "HttpInventory.java",
              "lineNumber": 160,
              "inProject": true
            },
            {
              "method": "java.lang.Thread.run",
              "file": "Thread.java",
              "lineNumber": 818
            }
          ]
        }
      ],
      "user": {
        "id": "316aaa43f369bb45"
      },
      "app": {
        "id": "org.flyve.inventory.agent",
        "name": "Inventory",
        "packageName": "org.flyve.inventory.agent",
        "versionName": "0.1.0",
        "versionCode": 39160,
        "version": "0.1.0",
        "releaseStage": "production"
      },
      "appState": {
        "duration": 60783,
        "inForeground": true,
        "activeScreen": "org.flyve.inventory.agent.FragmentAccueil",
        "memoryUsage": 13814088,
        "lowMemory": false
      },
      "device": {
        "osName": "android",
        "manufacturer": "LENOVO",
        "brand": "Lenovo",
        "model": "Lenovo TB2-X30F",
        "id": "316aaa43f369bb45",
        "apiLevel": 23,
        "osVersion": "6.0.1",
        "osBuild": "TB2-X30F_S000113_160816_ROW",
        "locale": "fr_FR",
        "totalMemory": 134217728,
        "jailbroken": false,
        "screenDensity": 1,
        "dpi": 160,
        "screenResolution": "1280x752"
      },
      "deviceState": {
        "freeMemory": 120401832,
        "orientation": "landscape",
        "batteryLevel": 1,
        "freeDisk": 11950485504,
        "charging": false,
        "locationStatus": "allowed",
        "networkAccess": "wifi",
        "time": "2017-10-26T11:05:00Z"
      },
      "breadcrumbs": [
        
      ]
    }
  ]
}
```

**Comment by ildar** [comment]
I got similar crash because:

- Server address is cleared in Settings.

and I see fatal exception happen in logcat:

> 01-17 13:11:50.594  1740  1740 E InventoryAgent: [org.flyve.inventory.agent.utils.HttpInventory] Inventory server url is malformed, please check itProtocol not found: 
> 01-17 13:11:50.635  1740  1740 E InventoryAgent: [org.flyve.inventory.agent.utils.HttpInventory] The requested URL is not found, please check it
> 01-17 13:11:50.645  1740  2065 W System  : ClassLoader referenced unknown path: /system/framework/tcmclient.jar
> 01-17 13:11:50.747  1740  2065 E AndroidRuntime: FATAL EXCEPTION: Thread-1649
> 01-17 13:11:50.747  1740  2065 E AndroidRuntime: Process: org.flyve.inventory.agent, PID: 1740
> 01-17 13:11:50.747  1740  2065 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.net.URL.toExternalForm()' on a null object reference
> 01-17 13:11:50.747  1740  2065 E AndroidRuntime: 	at org.flyve.inventory.agent.utils.HttpInventory$1.run(HttpInventory.java:160)
> 01-17 13:11:50.747  1740  2065 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
> 01-17 13:11:50.749   621  1099 W ActivityManager:   Force finishing activity org.flyve.inventory.agent/.FragmentAccueil
> 01-17 13:11:51.732  1740  1740 E ActivityThread: Activity org.flyve.inventory.agent.FragmentAccueil has leaked IntentReceiver org.flyve.inventory.categories.Battery$1@65cb77d that was originally registered here. Are you missing a call to unregisterReceiver()?
> 01-17 13:11:51.732  1740  1740 E ActivityThread: android.app.IntentReceiverLeaked: Activity org.flyve.inventory.agent.FragmentAccueil has leaked IntentReceiver org.flyve.inventory.categories.Battery$1@65cb77d that was originally registered here. Are you missing a call to unregisterReceiver()?
> 01-17 13:11:51.732  1740  1740 E ActivityThread: 	at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:919)
> 01-17 13:11:51.732  1740  1740 E ActivityThread: 	at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:720)
> 01-17 13:11:51.732  1740  1740 E ActivityThread: 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1182)
> 01-17 13:11:51.732  1740  1740 E ActivityThread: 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1162)
> 01-17 13:11:51.732  1740  1740 E ActivityThread: 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1156)
> 01-17 13:11:51.732  1740  1740 E ActivityThread: 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:560)
> 01-17 13:11:51.732  1740  1740 E ActivityThread: 	at org.flyve.inventory.categories.Battery.<init>(Battery.java:107)
> 01-17 13:11:51.732  1740  1740 E ActivityThread: 	at java.lang.reflect.Constructor.newInstance(Native Method)
> 01-17 13:11:51.732  1740  1740 E ActivityThread: 	at org.flyve.inventory.InventoryTask.loadCategoriesClass(InventoryTask.java:146)
> 01-17 13:11:51.732  1740  1740 E ActivityThread: 	at org.flyve.inventory.InventoryTask.access$000(InventoryTask.java:50)
> 01-17 13:11:51.732  1740  1740 E ActivityThread: 	at org.flyve.inventory.InventoryTask$1.run(InventoryTask.java:168)
> 01-17 13:11:51.732  1740  1740 E ActivityThread: 	at java.lang.Thread.run(Thread.java:818)
> 01-17 13:11:53.185  1740  2065 I Process : Sending signal. PID: 1740 SIG: 9
