### ISSUE TITLE
First Release from CI

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/android-inventory-agent#117]
Hi, @rafaelje 

When we push into the master branch.
Could you run this command when no CHANGELOG.md is present in the root of the repository?

`npm run release -- --first-release`

Thank you.

**Comment by rafaelje** [comment]
This issue is ready

**Comment by ajsb85** [comment]
Reference: https://github.com/flyve-mdm/android-inventory-agent/pull/125
