### ISSUE TITLE
Responsive layout for small screen

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/android-inventory-agent#119]
Unwanted line break in the about page

![image](https://user-images.githubusercontent.com/663460/33080410-4faacc44-ced8-11e7-8f2c-e49b3f7b59bf.png)

**Comment by rafaelje** [comment]
This line is not about device resolution I test on 320x480 real device, this line is the Android status bar on API 16 we can try screenshot on newest devices to look better, but take more time to do it, this is the faster emulator take just 3 minutes to get ready on others take at least 10 minutes

**Comment by ajsb85** [comment]
Hi, @rafaelje 

So what do you want to do?
I agree to going faster in the CI.
Btw, the screen of the settings is missed.
And the screen "Show my Inventory" show the spinner.
I think you can take the spinner and the full inventory.
And why it's in English only? https://github.com/flyve-mdm/android-inventory-agent/issues/114

**Comment by rafaelje** [comment]
@ajsb85 

I add screenshot with the newest device API 25, I think we need better screenshot that possible, I check in deep how to implement this other screenshot when I try always broke the test, and that's why just show English this screen has set text, I'll fix it on issue #114

**Comment by rafaelje** [comment]
In circleci we cannot run API 25 in this moment, because at this time the dockers require more memory to run this emulator, we are waiting to improve this issue

**Comment by ajsb85** [comment]
Hi, @rafaelje 
Fill a new issue to work in all tests for API versions later.

**Comment by rafaelje** [comment]
I'll close this issue and open a new one with API test version
