### ISSUE TITLE
Hostname in inventory

### ISSUE THREAD

**Issue by btry** [flyve-mdm/android-inventory-agent#126]
I received the suggestion to use the hostname found in developer settings to give a name to the computer in the inventory data.

**Comment by rafaelje** [comment]
@btry I need more information on this issue, where I go to add the hostname to the XML? 
I cannot find a TAG with name or something similar

**Comment by rafaelje** [comment]
Here some information about where to find the hostname on Android:

https://stackoverflow.com/questions/21898456/get-android-wifi-net-hostname-from-code

```
import android.os.Build;
import java.lang.reflect.Method;

/**
 * Retrieves the net.hostname system property
 * @param defValue the value to be returned if the hostname could
 * not be resolved
 */
public static String getHostName(String defValue) {
    try {
        Method getString = Build.class.getDeclaredMethod("getString", String.class);
        getString.setAccessible(true);
        return getString.invoke(null, "net.hostname").toString();
    } catch (Exception ex) {
        return defValue;
    }
}
```

**Comment by btry** [comment]
Hi

The hostname is stored in ```REQUEST/CONTENT/HARDWARE/NAME```.

By the way, do you think we could also change the name of the device ? (this is just an idea of new policy)

**Comment by Ivans51** [comment]
Is possible change the hostname device with root permission
https://stackoverflow.com/a/24289462

Example:
```
shell@A2010-l:/ $ su
root@A2010-l:/ # setprop net.hostname teclib-host
root@A2010-l:/ # getprop net.hostname
teclib-host
```

**Comment by btry** [comment]
Then we may plan a policy for Flyve 2.1. We have a flag to telle if a policy needs sytem permissions.

Fond the minimum version of Android where the feature is available
