### ISSUE TITLE
Camera permission

### ISSUE THREAD

**Issue by ildar** [flyve-mdm/android-inventory-agent#129]
1st thing app does is asking Camera permission. Hm! I can hardly guess what's that for, maybe for getting inventory...
2nd, if the app fails to get this permission, it stops. That's wrong. If the app didn't get a permission, that could be for a reason. Don't stop, do your job, app!
3rd, after I gave the Camera permission, the app failed to connect to Camera service and it made app stop again.
Please clarify/fix.

**Comment by rafaelje** [comment]
Hello @ildar thanks for your issue I'll response your questions:

1.- Yes this permission is required to get camera information.
2.- You are right I need to find a way to continue with the job if this permission fail
3.- In the same way I'll check why the library is stopping

Thanks for your comment I'll keep open your issue and working on it soon

**Comment by rafaelje** [comment]
@ildar I try to reproduce this error but is working for me can you help me with your android version like 8.0, 7.1, 5.0 or Oreo, Lolipop, etc,

Thanks!

**Comment by ildar** [comment]
Android 6.0.1 Resurrection Remix

**Comment by rafaelje** [comment]
@ildar I'm checking other issues now but I'll work on this
