### ISSUE TITLE
Spyware behavior

### ISSUE THREAD

**Issue by ildar** [flyve-mdm/android-inventory-agent#131]
I removed URL in Server address.
Push "Run inventory now". It answers: "Fail to connect to camera service".
At the same time my firewall reports that it blocked tcp connection to 104.27.153.236:443 and 104.27.152.236:443 from the app.
Question: what's that? Why on earth the app would want to connect to internet with empty Server address?

**Comment by rafaelje** [comment]
@ildar We have a crash report service and this is the connection, you can stop sending this information unckecking Heath Report and Usage Data in privacy section of Global Settings,

We are working on more privacy options

**Comment by ildar** [comment]
Oh, ok. Sorry.

**Comment by rafaelje** [comment]
Don't worry @ildar thanks for the advice!

I hope to read about you soon with more information
