### ISSUE TITLE
Add Test for new Android API version 

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/android-inventory-agent#136]
At this moment on CircleCI we can run just the API 16 because the others API require more memory to run and crash or take more than 30 minutes to connect and success in some case,

I think we can do this:
- Wait for the possibility to run with acceleration or x86 on CircleCI the say that maybe come probably this year

`x86 support is planned but I can’t guarantee a timeline. Probably 2018.`
https://discuss.circleci.com/t/kvm-emulation/9810/4

In this thread comment about increased the memory with `resource_class: large` but this is available for a paid account:
https://discuss.circleci.com/t/circle-ci-v2-and-android-memory-issues/11207/16
https://circleci.com/docs/2.0/configuration-reference/#resource_class

- Work to improve the memory and the simulator to get the better performance, test with the newest version of the emulator every time arrive one

I try with options like this and does not work:
```
emulator -avd test -noaudio -no-boot-anim -no-window -accel on
```

I try with this other options too:
https://circleci.com/docs/1.0/oom/#out-of-memory-errors-in-android-builds

**Comment by Ivans51** [comment]
Now firebase have support to this
