### ISSUE TITLE
Implement a adaptive icon for Android N

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/android-inventory-agent#144]
#### Observed Results:

The icon is not adapted to Android N or above
  
#### Expected behavior:

implement Adaptive Icons

https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html

**Comment by carlosgub** [comment]
Hi, what icons aren't adapted to android N?

**Comment by ajsb85** [comment]
Hi, @carlosgub 
This task is already done.
But you can download and try it and review to propose any improvement.

Thank you



> Teclib'
> 
> Teclib' has invited you to a testing program for an unreleased version of the Inventory Agent app.
> 
> As a tester, you'll receive an update that includes a testing version of the Inventory Agent app. Please note that testing versions may be unstable or have a few bugs.
> 
> https://play.google.com/apps/testing/org.flyve.inventory.agent
