### ISSUE TITLE
Transifex source string in English

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/android-inventory-agent#147]
Reference: 
https://www.transifex.com/flyve-mdm/android-inventory-agent/translate/#cs_CZ/value_timexml/117701186

**Comment by Ivans51** [comment]
This information is https://github.com/flyve-mdm/android-inventory-agent/blob/2aa01c91aaa1c8d4406f840e1b6be3a6711b51a9/app/src/main/res/values/strings.xml#L57

I will close this issue
