### ISSUE TITLE
XML not well formed in some specific cases

### ISSUE THREAD

**Issue by btry** [flyve-mdm/android-inventory-agent#148]
Hi

With the MDM agent, a Sony Z2 cannot enroll.

Fusion Inventory fails to import the XML. If I extract the XML and import manually I get a XML not well formed error.

Indeed, we need some escaping when a **&**  character appears in the text.

```xml
    <SENSORS>
      <NAME>APDS-9930/QPDS-T930 Proximity & Light</NAME>
      <NAME>Avago</NAME>
      <TYPE>PROXIMITY</TYPE>
      <POWER>12.675</POWER>
      <VERSION>2</VERSION>
    </SENSORS>
```

**Comment by Ivans51** [comment]
This issue is to https://github.com/flyve-mdm/android-inventory-library due that the output is generate  by the library
