### ISSUE TITLE
Submit application to F-Droid

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/android-inventory-agent#15]
Hi, @rafaelje 

Could you follow these steps to submit the application to F-Droid?

### Template to discuss the inclusion on F-Droid

* [x] The app complies with the [inclusion citeria](https://f-droid.org/wiki/page/Inclusion_Policy)
* [x] The app is not already listed in the repo or issue tracker.
* [x] The original app author has been notified (and supports the inclusion).

---------------------

### Link to the source code: 

https://github.com/flyve-mdm/flyve-mdm-android-inventory-agent

### Link to app in another app store: 

https://play.google.com/store/apps/details?id=org.flyve.inventory.agent

### License used: 

GPLv3

### Description: 

Flyve MDM is an open source mobile device management software (SaaS), that enables you to secure and manage all the mobile devices of your business via a unique web-based console (MDM). 
Our app makes IT Administrators daily life much easier! It offers them a wide range of enhanced functions, to efficiently manage the entire mobile fleet of the company in just a few clicks.

---
Related links:
- https://f-droid.org/contribute/
- https://forum.f-droid.org/
- https://f-droid.org/forums/forum/submission-queue/
- https://f-droid.org/wiki/page/Inclusion_Policy
- https://f-droid.org/manual/

Ref: https://github.com/flyve-mdm/flyve-mdm-android-inventory-agent/issues/5

**Comment by rafaelje** [comment]
To submit a new app on F-Droid I need to create a Merge Request on Gitlab with a .txt information:

Is important create a new release on Github,



```
Categories: Productivity
License:GPL-3.0
Author Name:Rafael Hernandez
Author Email:rhernandez@teclib.com
Web Site:https://github.com/flyve-mdm/flyve-mdm-android-inventory-agent
Source Code:https://github.com/flyve-mdm/flyve-mdm-android-inventory-agent
Issue Tracker:https://github.com/flyve-mdm/flyve-mdm-android-inventory-agent/issues

Auto Name:Flyve MDM Inventory Agent
Summary:This application is the Android inventory agent of the Inventory project
Description:
It features a complete inventory of your Android devices: both hardware and software information is collected. You get the data about processor, memory, drives, sensors, etc. and also the list and description of installed application (apk).

Inventory Agent for Android can send inventory to:

Inventory for GLPI 2.3.x and higher
OCSInventory NG (ocsng) 1.3.x and 2.x
Mandriva Pulse2
The Inventory project is an open source project providing :

Hardware and software inventory (multiplatform)
Network discovery
Network inventory for printers and switches
Wake On Lan (WOL)
Software deployment

Total integration with the GLPI project (open source asset management software and helpdesk)
Inventory agents can also be used with other open sources projects like Uranos or Rudder.

Repo Type:git
Repo:git@github.com:flyve-mdm/flyve-mdm-android-inventory-agent.git

Build:0.5,1
    commit=v0.5
    subdir=app
    gradle=yes

Auto Update Mode:Version v%v
Update Check Mode:Tags
```

**Comment by ajsb85** [comment]
Hi, @rafaelje 

Could you provide here the URL of the Merge Request in F-Droid?

Thanks.

**Comment by ajsb85** [comment]
Hi, @rafaelje 

Could you provide here the URL of the Merge Request in F-Droid?

Thanks.

**Comment by ajsb85** [comment]
Hi, @rafaelje 

Could you provide here the URL of the Merge Request of GitLab in F-Droid?

Thanks.

**Comment by rafaelje** [comment]
Hi @ajsb85!

This is the Merge Request URL:
https://gitlab.com/fdroid/fdroiddata/merge_requests/2597

**Comment by ajsb85** [comment]
Hi, @Naylin15 

Could you change the link to download the package from f-droid?

Reference:
https://f-droid.org/packages/org.flyve.inventory.agent/

![image](https://user-images.githubusercontent.com/663460/34963577-9108bf74-fa49-11e7-9a51-e15a707f53f3.png)
