### ISSUE TITLE
Spanish source strings on Transifex

### ISSUE THREAD

**Issue by Naylin15** [flyve-mdm/android-inventory-agent#153]
#### Observed Results:
The translator from the Czech language found out that the time values strings were in Spanish instead of English

Ref: [time values in Spanish](https://www.transifex.com/flyve-mdm/android-inventory-agent/translate/#cs_CZ/value_timexml/117701183)

  
#### Expected behavior:
The strings in English

**Comment by Ivans51** [comment]
The values times removed in transifex, i will close this
