### ISSUE TITLE
Bugsnag  java.lang.NullPointerException

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/android-inventory-agent#157]
java.lang.NullPointerException ·LauncherAttempt to invoke virtual method 'java.lang.String java.net.URL.toExternalForm()' on a null object reference
--

HttpInventory.java:160 · org.flyve.inventory.agent.utils.HttpInventory$1.run

**Comment by ajsb85** [comment]
Hi, @rafaelje 
This issue is very unclear.
Please, be a little bit more formal 😝

**Comment by Ivans51** [comment]
Hi, @rafaelje 
I can't duplicate the bug

**Comment by Ivans51** [comment]
No is possible to replicate the NullPointerException, I going closed this issue

**Comment by ajsb85** [comment]
Hi, @Ivans51 

Here is the line of the issue:
https://git.io/fxcBk

**Comment by ajsb85** [comment]
![image](https://user-images.githubusercontent.com/663460/46694853-2b212100-cc0e-11e8-8c29-95358e645ff6.png)

**Comment by ajsb85** [comment]
Maybe it was solved here:
https://git.io/fxcBC
