### ISSUE TITLE
android.view.WindowManager$BadTokenException ·ActivityMain

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/android-inventory-agent#165]
Unable to add window -- token android.os.BinderProxy@d69895c is not valid; is your activity running?

Severity error unhandled.dd127ba08dd0a0ff556d1759424e22e4
ReportModel.java:70 · org.flyve.inventory.agent.core.report.ReportModel.load
ReportModel.java:45 · org.flyve.inventory.agent.core.report.ReportModel.access$000
ReportModel.java:58 · org.flyve.inventory.agent.core.report.ReportModel$1.onTaskSuccess

**Comment by rafaelje** [comment]
This problem is still present

**Comment by Ivans51** [comment]
This crash is due a this https://stackoverflow.com/a/10509848

**Solution**
Change the behavior of the progress
