### ISSUE TITLE
Incorrect install date  format

### ISSUE THREAD

**Issue by btry** [flyve-mdm/android-inventory-agent#185]
**Describe the bug**
the mdm agent reports a timestamp for install date of software

```xml
    <SOFTWARES>
      <NAME>Jitsi Meet</NAME>
      <COMMENTS>org.jitsi.meet</COMMENTS>
      <VERSION>1.16.91</VERSION>
      <FILESIZE>0</FILESIZE>
      <FROM>Android</FROM>
      <INSTALLDATE>1521231589941</INSTALLDATE>
    </SOFTWARES>
    <SOFTWARES>
```

**To Reproduce**
1. use an enrolled agent
2. run an inventory from the console (glpi or dashboard)
3. read the list of software of the device, see the install date column

**Expected behavior**
the date should be readable. From unit tests of fusion inventory I read this example

```php
      $a_software['SOFTWARES'][] = [
                'ARCH'             => 'i586',
                'FROM'             => 'registry',
                'GUID'             => 'Audacity_is1',
                'HELPLINK'         => 'http://audacity.sourceforge.net',
                'INSTALLDATE'      => '16/10/2013',
                'NAME'             => 'Audacity 2.0.4',
                'PUBLISHER'        => 'Audacity Team',
                'UNINSTALL_STRING' => '"C:\\Program Files\\Audacity\\unins000.exe\"',
                'URL_INFO_ABOUT'   => 'http://audacity.sourceforge.net',
                'VERSION'          => '2.0.4',
                'VERSION_MAJOR'    => '2',
                'VERSION_MINOR'    => '0',
                'SYSTEM_CATEGORY'  => 'application'
            ];
```

warning: not sure though that this is the definitive solution. need a test to ensure the date is reported correctly. Notice it is DD/MM/YYYY
**Screenshots**

![image](https://user-images.githubusercontent.com/14139801/44523612-c439be00-a6da-11e8-95d4-a3ffc290ca74.png)

**Comment by Ivans51** [comment]
This issue is to https://github.com/flyve-mdm/android-inventory-library due that the output of the softwares is generated by the library

**Comment by ajsb85** [comment]
Hi, @btry 
Please test it in the beta version to confirm that is already fixed.
