### ISSUE TITLE
SIM cards

### ISSUE THREAD

**Issue by b-keller** [flyve-mdm/android-inventory-agent#188]
Hi,

In android inventory agent "data collected" I see "SIM Cards" but when I run an inventory no informations are imported in FusionInventory nor GLPI... I missed something?

 - Device: SM-A320FL
 - OS: Oreo (Android 8.0) api 26
 - inventory agent : 1.0.0-rc.1 
- GLPI server : 9.2.2 + FusionInventory : 9.2+1.0

[Computer-649.xml.txt](https://github.com/flyve-mdm/android-inventory-agent/files/2364597/Computer-649.xml.txt)

Thanks

**Comment by Ivans51** [comment]
This problem is due to FusionInventory that no shown this information
I create an issue https://github.com/fusioninventory/fusioninventory-for-glpi/issues/2733
I will close this issue
