### ISSUE TITLE
Header disappeared

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/android-inventory-agent#89]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/flyve-mdm/flyve-mdm-ios-inventory-agent/blob/develop/CONTRIBUTING.md#questions-or-doubts
</code></pre>

## Current behavior

Header with the logo hidden.

![image](https://user-images.githubusercontent.com/663460/31737205-09aff986-b447-11e7-837e-efd371bb6b6f.png)

## Expected behavior

Inventory Agent header.

## Environment
<pre><code>
Inventory Agent Version: 0.1.0 (901)

</code></pre>

**Comment by rafaelje** [comment]
This is an important issue to add the header again, we need to change the initial base app that is a PreferenceActivity for an Activity

**Comment by ajsb85** [comment]
Hi, @marcoscolina

Help us with this screen layout in the process to solve this issue

**Comment by bootbeep** [comment]
I'll let you know my thoughts. Thanks for the mention.
