### ISSUE TITLE
The agent version is not sent 

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/android-inventory-agent#91]
Hi, @rafaelje 

Could you use the `SemVer` of the Inventory Agent as argument for the library to generate the inventory?

I think it's a feature request for the library and the Agent

Thanks.

/cc @ticgal

![image](https://user-images.githubusercontent.com/663460/31765789-d8d55994-b4c5-11e7-9407-5a4a1322b174.png)

**Comment by rafaelje** [comment]
@ajsb85 I need more information about this issue I try to understand with @DIOHz0r we don't know what `SemVer` means please if you can help us

**Comment by ajsb85** [comment]
Hi, @rafaelje 

Here is the same screenshot but with a red mark

![image](https://user-images.githubusercontent.com/663460/35360110-e78cde24-015c-11e8-97d9-117e3ccc57c0.png)

**Comment by ajsb85** [comment]
> SemVer = Semantic Versioning

Is the version name of the Inventory Agent, example: `2.1.0`
https://semver.org/

**Comment by ajsb85** [comment]
Hi, @g-bougard
Could you help us with this issue?
Thanks.

Any another feedback from you @ticgal?

**Comment by g-bougard** [comment]
Hi @ajsb85 
to understand what to set you can check [communication.class.php plugin file](https://github.com/fusioninventory/fusioninventory-for-glpi/blob/master/inc/communication.class.php#L202) between L202 & L222.
Actually, you can define `REQUEST -> CONTENT -> MODULEVERSION`. Actually only NetInventory & NetDiscovery tasks are using this. Here is an example result:
```
<?xml version="1.0" encoding="UTF-8" ?>
<REQUEST>
  <CONTENT>
    <DEVICE>
...
    </DEVICE>
    <MODULEVERSION>2.6</MODULEVERSION>
    <PROCESSNUMBER>1</PROCESSNUMBER>
  </CONTENT>
  <DEVICEID>foo</DEVICEID>
  <QUERY>SNMPQUERY</QUERY>
</REQUEST>
```

For an inventory provided by FusionInventory agent, the version would be extracted from `REQUEST -> CONTENT -> VERSIONCLIENT` which is also reported as user-agent. This should give "v2.4" for `FusionInventory-Agent_v2.4`.

In your case, `REQUEST -> QUERY` should of course be set to `INVENTORY`.

**Comment by rafaelje** [comment]
Thanks for the information
