### ISSUE TITLE
Tag is not sent

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/android-inventory-agent#92]
Hi, @rafaelje 

@ticgal report that the FusionInventory tag is not sent (this is more important because it affects the assignment of users).

**Comment by rafaelje** [comment]
I need more information about this issue what TAG is missing?

I'm working based on this document:
http://fusioninventory.org/documentation/dev/spec/protocol/inventory.html

**Comment by rafaelje** [comment]
I see this issue is related maybe with @DIOHz0r we can find where is the FusionInventory Tag that appear in the screenshot:

https://github.com/flyve-mdm/android-inventory-agent/issues/91

**Comment by ajsb85** [comment]
PING @TICgal

**Comment by joschi99** [comment]
Same problem. Is there any solution? Do you need additional informations?

**Comment by rafaelje** [comment]
@joschi99 could you try with this version https://play.google.com/apps/testing/org.flyve.inventory.agent

**Comment by joschi99** [comment]
Hi @rafaelje,
I tried out the beta app but the asset on Fusioninventory is without tag. Device will be imported still on root entity.

**Comment by rafaelje** [comment]
Hi @joschi99 we are going to make an official release very soon, at this moment the lasted version is on test

**Comment by joschi99** [comment]
Hi @rafaelje,
unfortunately the beta version has still the issue with the missing TAG. Do you think that the official release resolves this problem? Do you have a timeline for the release?

For us the TAG is important because we made the entity routing through the TAG.

Best regards,
Jochen
