### ISSUE TITLE
Compatibility Matrix

### ISSUE THREAD

**Issue by ajsb85** [flyve-mdm/android-inventory-agent#93]
Hi, @rafaelje 

Could you add a compatibility matrix to the README file?

Similar to this format:

|GLPI|9.1.1|9.1.2|9.1.3|9.2.0|
|:----|----|----|----|---|
|**Flyve MDM**|1.x.x|1.x.x|1.x.x| 2.0.0-dev |
|**FusionInventory**|9.1-1.1|9.1-1.1|9.1-1.1|master branch|

@ticgal reported the usage from `GLPI 9.1.4 y FusionInventory 9.1+1.1.`

And we can keep this issue to report any another version of GLPI and FI

**Comment by ajsb85** [comment]
Hi, @Naylin15 

Could you write the draft about the Compatibility Matrix?
And @rafaelje provide some initial versions already under test.

Thanks.

**Comment by ajsb85** [comment]
I added a new compatibility table with only MINOR versions.

|GLPI|9.1|9.2|
|:---|:---:|:---:|
|**Flyve MDM**|1.0||
|**FusionInventory**|9.1+1.1||

We need to deploy multiples versions of FI to test it 👍

**Comment by ajsb85** [comment]
Hi, @DIOHz0r 
Help us to build this list.
Test all versions of the inventory agent, and all versions of the FusionInventory plugin + GLPI.
Thank you.

**Comment by Naylin15** [comment]
Hi, 

I'll be closing this issue since the matrix is already added and up-to-date
